---
- name: check exceptions
  shell: 'grep  "^skip-cron-check:.*{{ ansible_facts.hostname }}" /usr/ust/etc/validation-exceptions >/dev/null 2>&1'
  ignore_errors: true
  register: exception_found

- block:

  - name: confirm cron entries
    ansible.builtin.cron:
      cron_file: "{{ item.cron_file }}"
      name: "{{ item.name }}"
      job: "{{ item.cron_entry }}"
      hour: "{{ item.hour }}"
      minute: "{{ item.minute }}"
      month: "{{ item.month }}"
      user: root
      backup: yes

    loop:
      - name: "audit_security"
        cron_entry: "/usr/ust/scripts/audit/security"
        hour: "4"
        minute: "30"
        month: "*"
        cron_file: "cop_srvr_base"
      - name: "sar_report"
        cron_entry: "/usr/ust/scripts/sarrpt"
        hour: "23"
        minute: "58"
        month: "*"
        cron_file: "cop_srvr_performance"
      - name: "sar_monthly_avg"
        cron_entry: "/usr/ust/scripts/sarmonavg"
        hour: "1"
        minute: "0"
        month: "1"
        cron_file: "cop_srvr_base"
      - name: "pwd_exp_warn"
        cron_entry: "/usr/ust/scripts/passwd_expire_warning"
        hour: "0"
        minute: "10"
        month: "*"
        cron_file: "cop_srvr_base"
      - name: "netstat_report"
        cron_entry: "/usr/ust/scripts/netstat_report.LINUX"
        hour: "*"
        minute: "*/10"
        month: "*"
        cron_file: "cop_srvr_base"
      - name: "mon_roll_wtmp"
        cron_entry: "/usr/ust/scripts/monthly_roll_wtmp"
        hour: "2"
        minute: "0"
        month: "*"
        cron_file: "cop_srvr_base"
      - name: "sys_alive"
        cron_entry: "/usr/ust/scripts/systemalivelogger"
        hour: "*"
        minute: "*/15"
        month: "*"
        cron_file: "cop_srvr_base"
      - name: "kill_hung"
        cron_entry: "/usr/ust/scripts/kill_hung_processes"
        hour: "6"
        minute: "0"
        month: "*"
        cron_file: "cop_srvr_base"
      - name: "cp_pwd_file"
        cron_entry: "/usr/ust/scripts/cp_passwd_file"
        hour: "2"
        minute: "0"
        month: "*"
        cron_file: "cop_srvr_base"
      - name: "sudo_sync"
        cron_entry: "/usr/ust/scripts/sudo_sync"
        hour: "*"
        minute: "*/10"
        month: "*"
        cron_file: "cop_srvr_base"
      - name: "perfman"
        cron_entry: "/usr/ust/scripts/performance/perfman"
        hour: "*"
        minute: "0"
        month: "*"
        cron_file: "cop_srvr_performance"
      - name: "validate"
        cron_entry: "/usr/ust/scripts/validate"
        hour: "4"
        minute: "40"
        month: "*"
        cron_file: "cop_srvr_base"
      - name: "ppcoperf"
        cron_entry: "/usr/ust/scripts/ppcoperf"
        hour: "0"
        minute: "5"
        month: "*"
        cron_file: "cop_srvr_performance"
      - name: "ppcoperf_psdata"
        cron_entry: "/usr/ust/scripts/ppcoperf_psdata_lnx"
        hour: "*"
        minute: "*/10"
        month: "*"
        cron_file: "cop_srvr_performance"
      - name: "ppcoiostat"
        cron_entry: "/usr/ust/scripts/ppcoiostat_linux"
        hour: "*"
        minute: "*/10"
        month: "*"
        cron_file: "cop_srvr_performance"
      - name: "paging"
        cron_entry: "/usr/ust/scripts/paging 600 144"
        hour: "0"
        minute: "0"
        month: "*"
        cron_file: "cop_srvr_performance"
 
  when: exception_found.rc != 0


- name: write check_cron to log
  blockinfile:
    path: /usr/local/logs/validation.{{ ansible_hostname }}.testoutput
    block: " checked/confirmed cron entries "
    insertbefore:
    marker: "---------------- {mark} check_cron.yml --------------------"
