---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

# below task simply prints all installed packages for testing
#- name: Print package facts
#  debug:
#    var: ansible_facts.packages

- name: "Check if packages are installed"
  debug:
    msg: "{{ ansible_facts.packages[item], omit }}"
  loop: "{{ package_names }}"
  