---
- name: "Check if package {{ item }} is installed"
  command: rpm -q "{{ item }}"
  loop: "{{ package_names }}"
  register: package_check

- name: "Print package check results"
  debug:
    msg: "The package requested is installed: {{ package_check.item }}"
  when: package_check is succeeded
