---
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

# below task simply prints all installed packages for testing
#- name: Print package facts
#  debug:
#    var: ansible_facts.packages

- name: "Check if packages are installed"
  ignore_errors: True
  debug:
    msg: "{{ item }} is installed on {{ inventory_hostname }}"
  when: item in ansible_facts.packages
  loop: "{{ package_names }}"

- name: "Print packages NOT installed"
  debug:
    msg: "{{ item }} is not installed on {{ inventory_hostname }}"
  when: item is not in ansible_facts.packages
  loop: "{{ package_names }}"